* emacs-maple-translate
  Translate words between Chinese and English.

** Installation
   #+begin_src elisp
   (use-package maple-translate
     :quelpa (:fetcher github :repo "honmaple/emacs-maple-translate")
     :commands (maple-translate maple-translate+))
   #+end_src

   Or alternatively, you can download the repository and install manually by doing:
   #+begin_src bash
   git clone https://github.com/honmaple/emacs-maple-translate ~/.emacs.d/site-lisp/maple-translate
   #+end_src

   #+begin_src elisp
   (use-package maple-translate
     :ensure nil
     :commands (maple-translate maple-translate+))
   #+end_src

** Usage

In any buffer, run =M-x maple-translate= to translate the selected text or the
word at point. By default, it translates the input to Chinese, as the default
backends are for English-Chinese translation. See the Customization section for
configuring other backends.

** Customization
*** Basic settings
    #+begin_src emacs-lisp
      (use-package maple-translate
        :load-path (lambda() (expand-file-name "~/.emacs.d/downloads/emacs-maple-translate"))
        :commands (maple-translate maple-translate+)
        :custom (maple-translate-engine 'youdao)
        :bind (:map global-map
                    ("C-h D" . maple-translate)
                    ("C-h d" . maple-translate+))
        )
    #+end_src
    The above example performs the following actions:
    - Loads the =emacs-maple-translate= repository from =~/.emacs.d/downloads=.
    - Sets =youdao= as the backend.
    - Binds =maple-translate= to =C-h D= and =maple-translate+= to =C-h d=.

*** Advanced settings
    #+begin_src elisp
    (add-to-list 'maple-translate-alist '(custom . custom-translate-function))
    (setq maple-translate-engine 'custom)
    ;; or use multi engines
    (setq maple-translate-engine '(youdao dictcn custom))

    ;; with google translate
    (setq maple-translate-google-url "https://translate.googleapis.com/translate_a/single")
    (setq maple-translate-google-proxies
          '(("http" . "127.0.0.1:1086")
            ("https" . "127.0.0.1:1086")))

    ;; with offline sdcv
    (setq maple-translate-sdcv-dir "~/.stardict/dicts")
    (setq maple-translate-sdcv-dicts
          '(("lazyworm-ec" . "stardict-lazyworm-ec-2.4.2")
            ("lazyworm-ce" . "stardict-lazyworm-ce-2.4.2")))
    #+end_src

** Offline
   - [X] Sdcv

** Long sentence
   - [X] Youdao
   - [X] Google

** Supported Engines
   - youdao
   - dictcn
   - iciba
   - bing
   - google
   - sdcv
